// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOg_s0zgIgloZLMqiIkQfpnHSJ698sdc',
    appId: '1:1025592273564:web:c2321e2292442420339b59',
    messagingSenderId: '1025592273564',
    projectId: 'movieapp-4bcbc',
    authDomain: 'movieapp-4bcbc.firebaseapp.com',
    storageBucket: 'movieapp-4bcbc.firebasestorage.app',
    measurementId: 'G-1J9XB0B343',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeHqHzRSGBLKX2fCI6bOSrrTewkDuG1Y',
    appId: '1:1025592273564:android:dcd159e6f86bf489339b59',
    messagingSenderId: '1025592273564',
    projectId: 'movieapp-4bcbc',
    storageBucket: 'movieapp-4bcbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlleZWo2H-I-dQdC9ymsLBz4K8o9BPbZo',
    appId: '1:1025592273564:ios:d2d1c413171cecc5339b59',
    messagingSenderId: '1025592273564',
    projectId: 'movieapp-4bcbc',
    storageBucket: 'movieapp-4bcbc.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlleZWo2H-I-dQdC9ymsLBz4K8o9BPbZo',
    appId: '1:1025592273564:ios:d2d1c413171cecc5339b59',
    messagingSenderId: '1025592273564',
    projectId: 'movieapp-4bcbc',
    storageBucket: 'movieapp-4bcbc.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOg_s0zgIgloZLMqiIkQfpnHSJ698sdc',
    appId: '1:1025592273564:web:652a2d92abd4f140339b59',
    messagingSenderId: '1025592273564',
    projectId: 'movieapp-4bcbc',
    authDomain: 'movieapp-4bcbc.firebaseapp.com',
    storageBucket: 'movieapp-4bcbc.firebasestorage.app',
    measurementId: 'G-3LD0DF92DY',
  );
}
